name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions with AZ CLI
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 7cf6f3df-9816-4404-a3af-a06c9658a5ed
          region: West US
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="West US"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Stroage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 7cf6f3df-9816-4404-a3af-a06c9658a5ed
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=bgglobostg002
            location="East US"
          deploymentMode: incremental

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 7cf6f3df-9816-4404-a3af-a06c9658a5ed
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword="My$secureP@ssw0rd!"
          deploymentMode: incremental
          
